### ISSUE TITLE
你的域名解析次数用完了

### ISSUE THREAD

**Issue by anglesgirl** [TulvL/cloudflare-ip-tester#3]

**Comment by anglesgirl** [comment]
> 请问有何提示？

geoscaling 提供的免费解析有限量
一段时间内请求数满后，就无法解析到任何ip

我已经第二次遇到了，解析不出ip后，去https://zijian.aliyun.com做检查，也是没有任何解析结果

**Comment by TulvL** [comment]
> geoscaling 提供的免费解析有限量
> 一段时间内请求数满后，就无法解析到任何ip
> 
> 我已经第二次遇到了，解析不出ip后，去[https://zijian.aliyun.com做检查，也是没有任何解析结果](https://zijian.aliyun.com%E5%81%9A%E6%A3%80%E6%9F%A5%EF%BC%8C%E4%B9%9F%E6%98%AF%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E8%A7%A3%E6%9E%90%E7%BB%93%E6%9E%9C)

我看了下，应该是 geoscaling 的 ns 挂了
