### ISSUE TITLE
Where is the data source of ip_list.csv?

### ISSUE THREAD

**Issue by xianshenglu** [TulvL/cloudflare-ip-tester#5]
Thanks for this great job. It helps me a lot. Anyway, just one question,
> Where is the data source of ip_list.csv?

It seems inconsistent with https://www.cloudflare.com/zh-cn/ips/. This is the only data I have found.
Anyway, thanks a lot.

**Comment by TulvL** [comment]
This list was made based on that link, and then I wrote a program to exclude unresponsive IP ranges.
